### ISSUE TITLE
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException

### ISSUE THREAD

**Issue by ewliang** [rosen-vladimirov/RemoveP12Password#1]
So I downloaded the windows exe file, ran the command, and it showed this.

```
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at RemoveP12Password.Program.Main(String[] args)
```

**Comment by ewliang** [comment]
Figured out my issue. Turns out because my Windows' User's name contains my first and last name, which shows up with a space in between in the file path
```
ex: C:\Users\Eric Liang\Documents\....
```
I had to surround the entire filepath in quotation marks.
```
The Result: 
"C:\Users\Eric Liang\Documents\..."
```
And it ran perfectly. :)
